### ISSUE TITLE
Odeslání dat na returnUrl

### ISSUE THREAD

**Issue by sinacek** [opendata-mvcr/lkod#3]
Nyní se data odesílají zpět do prohlížeče. To bych zachoval jako výchozí možnost, ale pokud se nadefinuje parametr `returnUrl`, tak se data pošlou tam jako JSON-LD pomocí metody POST

Například:
```js
{
    form-data: {} // JSON-LD data
}
```

**Comment by skodapetr** [comment]
S současné době se pošle application/x-www-form-urlencoded, ve stylu klasického HTML form, příklad je možné pozorovat třeba na:

https://dev.nkod.opendata.cz/formul%C3%A1%C5%99/registrace-datov%C3%A9-sady?returnUrl=https%3A%2F%2Fdev.nkod.opendata.cz%2Fformul%C3%A1%C5%99%2Fregistrace-datov%C3%A9-sady 

Pokud bude třeba můžeme přejít z application/x-www-form-urlencoded na content-type: application/ld+json, je to možné. Nicméně pak bude třeba si domluvit jakým mechanismem bude stránka opuštěna. Neb využití současného přístupu zároveň udělá refresh stránky a umožní tak třeba návrat do systému třeští strany. Příkladem je link výše jenž udělá vlastně POST sám na sebe a tedy ukazuje jako returnUrl tak ožnost POST dat.

**Comment by sinacek** [comment]
díky, to by mělo vyhovovat
