### ISSUE TITLE
Možnost uložení vlastních dat

### ISSUE THREAD

**Issue by sinacek** [opendata-mvcr/lkod#4]
Pro komunikaci s naším systémem potřebujume si ve formuláři uchovat vlastní JSON, který pak potřebujeme nezměněný jen poslat zpět. Cílem je držet například ID datové sady, token na ověření, že se jedná o platný požadavek apod.

**Comment by skodapetr** [comment]
@sinacek Co znamená "uchovat" a poslat zpět? Respektive v jaké podobě - samostný field v POST requestu, nebo properta v JSON objektu vedle samotných dat fomuláře? 
Bylo by možné poskytnout nějaký příklad? Třeba pomocí CURLu ?

**Comment by sinacek** [comment]
Měla by to být vlastní property v JSON objektu vedle samotných dat formuláře a bude to taky zase JSON objekt.

**Comment by skodapetr** [comment]
Použití vlastních dat je ukázané v dotazech na https://github.com/opendata-mvcr/lkod/issues/2 .
