### ISSUE TITLE
Zachovat IRI distribuce

### ISSUE THREAD

**Issue by sinacek** [opendata-mvcr/lkod#6]
Při nahrání datové sady do formuláře a následné uložení se mi nezahová IRI u distribucí, což bych potřeboval.

**Comment by sinacek** [comment]
Tušíte kdy se to bude realizovat?

**Comment by jakubklimek** [comment]
@sinacek Mělo by to být, jen jsem to ještě netestoval.

**Comment by jakubklimek** [comment]
@sinacek Zkusil jsem to a zdá se že funguje. Nicméně to samé asi bude potřeba i pro IRI datové služby, že?

**Comment by sinacek** [comment]
> @sinacek Zkusil jsem to a zdá se že funguje. Nicméně to samé asi bude potřeba i pro IRI datové služby, že?

To jsme zatím neřešili, ale tenhle princip budeme potřebovat všude, že co za IRI jsme poslali, tak bychom ho chtěli i dostat zpět.

**Comment by jakubklimek** [comment]
@sinacek  Mělo by to být implementováno dle diskuze ze Slacku. Tedy nové distribuce a služby jsou blank nody, ty co měly IRI tak jejich IRI je zachováno.
